site_name: VUBRacing Driverless Wiki
nav:
  - Home: home.md
  - Onboarding: onboarding.md
  - Software: software.md
  - Hardware: hardware.md
  - Processes: processes.md
  - References: references.md

theme: readthedocs
